exports.presets =
	'Sans-serif':
			xHeight: 520
			capDelta: 230
			ascender: 230
			descender: -250
			crossbar: 1
			width: 1
			roundness: 0.65
			thickness: 115
			_contrast: -1
			breakPath: 1
			aperture: 1
			axis: 0
			serifMedian: 1
			serifWidth: 0
			serifHeight: 0
			serifCurve: 15
			serifArc: 0
			serifTerminal: 0
			serifRotate: 1
			serifRoundness : 1
			midWidth: 1
			serifTerminalCurve: 1
			spurHeight: 1
			overshoot: 10
			slant: 0
			curviness: 0.6
			opticThickness: 1
			serifBall: 1

	'Old Style':
		xHeight: 520
		capDelta: 230
		ascender: 230
		descender: -250
		crossbar: 1
		width: 1
		roundness: 0.65
		thickness: 115
		_contrast: -1
		breakPath: 1
		aperture: 1
		axis: 0
		serifMedian: 1
		serifWidth: 0
		serifHeight: 0
		serifCurve: 15
		serifArc: 0
		serifTerminal: 0
		serifRotate: 1
		serifRoundness : 1
		midWidth: 1
		serifTerminalCurve: 1
		spurHeight: 1
		overshoot: 10
		slant: 0
		curviness: 0.6
		opticThickness: 1
		serifBall: 1

	'Modern':
		xHeight: 520
		capDelta: 230
		ascender: 230
		descender: -250
		crossbar: 1
		width: 1
		roundness: 0.65
		thickness: 115
		_contrast: -1
		breakPath: 1
		aperture: 1
		axis: 0
		serifMedian: 1
		serifWidth: 0
		serifHeight: 0
		serifCurve: 15
		serifArc: 0
		serifTerminal: 0
		serifRotate: 1
		serifRoundness : 1
		midWidth: 1
		serifTerminalCurve: 1
		spurHeight: 1
		overshoot: 10
		slant: 0
		curviness: 0.6
		opticThickness: 1
		serifBall: 1

	'Slab':
		xHeight: 520
		capDelta: 230
		ascender: 230
		descender: -250
		crossbar: 1
		width: 1
		roundness: 0.65
		thickness: 115
		_contrast: -1
		breakPath: 1
		aperture: 1
		axis: 0
		serifMedian: 1
		serifWidth: 0
		serifHeight: 0
		serifCurve: 15
		serifArc: 0
		serifTerminal: 0
		serifRotate: 1
		serifRoundness : 1
		midWidth: 1
		serifTerminalCurve: 1
		spurHeight: 1
		overshoot: 10
		slant: 0
		curviness: 0.6
		opticThickness: 1
		serifBall: 1

	'Blackletter':
		xHeight: 520
		capDelta: 230
		ascender: 230
		descender: -250
		crossbar: 1
		width: 1
		roundness: 0.65
		thickness: 115
		_contrast: -1
		breakPath: 1
		aperture: 1
		axis: 0
		serifMedian: 1
		serifWidth: 0
		serifHeight: 0
		serifCurve: 15
		serifArc: 0
		serifTerminal: 0
		serifRotate: 1
		serifRoundness : 1
		midWidth: 1
		serifTerminalCurve: 1
		spurHeight: 1
		overshoot: 10
		slant: 0
		curviness: 0.6
		opticThickness: 1
		serifBall: 1
